export default [
  "MdFitnessCenter",
  "MdFastfood",
  "MdDirectionsRun",
  "MdDirectionsBike",
  "MdPool",
  "MdLocalPizza",
  "MdCode",
  "MdGroups",
  "MdTv",
  "MdSentimentSatisfied",
  "MdPsychology",
  "MdPets",
  "MdWaterDrop",
  "MdRecycling",
  "MdStar",
  "MdTranslate",
];
